# Generated by Django 4.1.2 on 2022-10-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speakers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speakers_title', models.CharField(max_length=100, verbose_name='ФИО спикера')),
                ('speakers_descr', models.CharField(max_length=70, verbose_name='Долдность спикера')),
                ('speakers_inst', models.CharField(blank=True, max_length=100, null=True, verbose_name='Инстаграмм спикера')),
                ('speakers_photo', models.ImageField(upload_to='photo/', verbose_name='Фото спикера')),
                ('speakers_main', models.BooleanField(default=False, verbose_name='Избранный спикер?')),
                ('speakers_order', models.SmallIntegerField(default=0, verbose_name='Порядок')),
                ('speakers_draft', models.BooleanField(default=True, verbose_name='Публикация')),
            ],
            options={
                'verbose_name': 'Спикеры',
                'verbose_name_plural': 'Спикеры',
            },
        ),
        migrations.CreateModel(
            name='SpeakersMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголвок блока')),
                ('descr', models.TextField(verbose_name='Описание блока')),
            ],
            options={
                'verbose_name': 'Настройки блока Спикеров',
            },
        ),
    ]
