# Generated by Django 4.1.3 on 2022-11-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('form_email', models.EmailField(max_length=100, verbose_name='Email')),
                ('form_subject', models.CharField(max_length=100, verbose_name='Тема')),
                ('form_text', models.TextField(verbose_name='Текст письма')),
            ],
            options={
                'verbose_name': 'Заявки с формы',
                'verbose_name_plural': 'Заявки с формы',
            },
        ),
    ]
