# Generated by Django 4.1.2 on 2022-10-30 06:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('speakers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название собития')),
                ('decsr', models.TextField(verbose_name='Описание события')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo/', verbose_name='Фото события')),
                ('time_begin', models.TimeField(default=django.utils.timezone.now, verbose_name='Время начала')),
                ('time_end', models.TimeField(default=django.utils.timezone.now, verbose_name='Время окончания')),
                ('draft', models.BooleanField(default=True, verbose_name='Публикация')),
                ('speaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='speaker_schedule', to='speakers.speakers')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписание',
            },
        ),
    ]
