# Generated by Django 4.1.2 on 2022-10-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamblocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitem',
            name='place',
            field=models.CharField(default=1, max_length=60, verbose_name='Место проведения'),
            preserve_default=False,
        ),
    ]
