# Generated by Django 4.1.2 on 2022-10-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_schedule_options_alter_scheduleonpage_options_and_more'),
        ('streamblocks', '0002_scheduleitem_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitem',
            name='date_ivent',
            field=models.ManyToManyField(related_name='ivent_date', to='schedule.schedule', verbose_name='Даты ивента'),
        ),
        migrations.AlterField(
            model_name='scheduleitem',
            name='photo',
            field=models.ImageField(default=1, upload_to='photo/', verbose_name='Фото события'),
            preserve_default=False,
        ),
    ]
