# Generated by Django 4.1.2 on 2022-10-29 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=80, verbose_name='Title страницы')),
                ('main_description', models.CharField(max_length=255, verbose_name='Description страницы')),
                ('main_name', models.CharField(max_length=100, verbose_name='Название сайта')),
                ('main_copywrite', models.CharField(max_length=150, verbose_name='Копирайт в подвале')),
                ('main_fb', models.CharField(max_length=100, null=True, verbose_name='FB в подвале')),
                ('main_instagram', models.CharField(max_length=100, null=True, verbose_name='Instagram в подвале')),
                ('main_wa', models.CharField(max_length=100, null=True, verbose_name='WA в подвале')),
                ('main_yt', models.CharField(max_length=100, null=True, verbose_name='YouTube в подвале')),
            ],
            options={
                'verbose_name': 'Основные',
                'verbose_name_plural': 'Основные',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_title', models.CharField(max_length=50, verbose_name='Пукнт меню')),
                ('menu_url', models.CharField(max_length=50, verbose_name='Ссылка меню')),
                ('menu_footer', models.BooleanField(default=False, verbose_name='Отображать пункт меню в подвале')),
                ('menu_order', models.SmallIntegerField(default=0, verbose_name='Порядок')),
                ('menu_draft', models.BooleanField(default=True, verbose_name='Публикация')),
                ('id_menu', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='id_menu', to='main.main')),
            ],
            options={
                'verbose_name': 'Пункты меню',
                'verbose_name_plural': 'Пункты меню',
            },
        ),
    ]
