# Generated by Django 4.1.2 on 2022-10-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_main_main_fb_alter_main_main_instagram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BottomBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bottom_banner_title', models.CharField(max_length=50, verbose_name='Заголовок баннера')),
                ('bottom_banner_descr', models.TimeField(verbose_name='Описание на баннере')),
                ('bottom_banner_button', models.CharField(max_length=50, verbose_name='Название кнопки')),
                ('bottom_banner_button_url', models.CharField(help_text='Может быть задана ссылка на блок через #', max_length=80, verbose_name='Ссылка на кнопку')),
            ],
            options={
                'verbose_name': 'Нижний баннер',
            },
        ),
    ]
