# Generated by Django 4.1.2 on 2022-10-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_bottombanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottombanner',
            name='bottom_banner_descr',
            field=models.TextField(verbose_name='Описание на баннере'),
        ),
    ]
