# Generated by Django 4.1.2 on 2022-10-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_bottombanner_bottom_banner_descr'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_place_block_title', models.CharField(max_length=50, verbose_name='Заголовок блока')),
                ('main_place_title', models.CharField(max_length=60, verbose_name='Название места')),
                ('main_place_address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('main_place_email', models.EmailField(max_length=100, verbose_name='Email')),
                ('main_place_phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('main_place_map', models.CharField(help_text='Скрипт или фрэйм карты', max_length=255, verbose_name='Ссылка на карту')),
            ],
            options={
                'verbose_name': 'Место проведения',
            },
        ),
    ]
