# Generated by Django 4.1.2 on 2022-10-30 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'День проведения', 'verbose_name_plural': 'День проведения'},
        ),
        migrations.AlterModelOptions(
            name='scheduleonpage',
            options={'verbose_name': 'Расписание', 'verbose_name_plural': 'Расписание'},
        ),
        migrations.AddField(
            model_name='schedule',
            name='id_schedule',
            field=models.CharField(default=1, help_text='Пример: day_1', max_length=50, verbose_name='ID вкладки'),
            preserve_default=False,
        ),
    ]
