# Generated by Django 4.1.2 on 2022-10-29 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'Блок «О нас»'},
        ),
    ]
