# Generated by Django 4.1.2 on 2022-10-29 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_title_one', models.CharField(max_length=50, verbose_name='Подчеркнутый текст')),
                ('banner_title_two', models.CharField(max_length=50, verbose_name='Текст')),
                ('banner_date', models.CharField(max_length=50, verbose_name='Даты проведения')),
                ('banner_plase', models.CharField(max_length=50, verbose_name='Место проведения')),
                ('banner_movie', models.FileField(upload_to='banner/', verbose_name='Видео на фоне')),
            ],
            options={
                'verbose_name': 'Основной баннер',
            },
        ),
        migrations.CreateModel(
            name='BannerVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=50, verbose_name='Название')),
                ('video_url', models.CharField(max_length=200, verbose_name='Ссылка на видео')),
                ('video_prew', models.ImageField(upload_to='banner/', verbose_name='Превью видео')),
                ('video_order', models.SmallIntegerField(default=0, verbose_name='Порядок')),
                ('video_draft', models.BooleanField(default=True, verbose_name='Публикация')),
                ('id_video', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='id_video', to='banner.banner')),
            ],
            options={
                'verbose_name': 'Видео в баннере',
                'verbose_name_plural': 'Видео в банере',
            },
        ),
    ]
